name: Build LobsterPyGUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2' # Specify the Qt version you need
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        dir: '$HOME/Qt' # Optional: specify a custom installation directory
    - name: Set up Qt environment
      run: echo "$HOME/Qt/5.15.2/gcc_64/bin" >> $GITHUB_PATH
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential
    - name: Change to src directory
      working-directory: ./src
      run: echo "Changed directory to src"
    - name: Configure project with qmake
      working-directory: ./src
      run: qmake -project || true # This is optional if .pro file already exists
    - name: Generate Makefile with qmake
      working-directory: ./src
      run: qmake
    - name: Build project
      working-directory: ./src
      run: make

